### ISSUE TITLE
"Has a dog ever been..." answers incorrect (Google Feud)

### ISSUE THREAD

**Issue by TLTheLegend** [Ryan778/Ryan778.github.io#3]
Your Google Feud answers for "Has a dog ever been..." are incorrect. Your answers are, in order:
in space
on the moon
mayor
knighted
cloned
arrested
eaten by a shark
mated with a cat
struck by lightning
hit by lightning
However, Google Feud says its answers are:
mated with a cat
to space
mayor
arrested
struck by lightning
knighted
cloned
to the moon
cured of lymphoma
bred with a cat
I have attached a photo as proof. 
![Google Feud  Home of Autocomplete](https://user-images.githubusercontent.com/63113320/78377971-8d51ac80-758d-11ea-9474-617a847591b9.png)
I would appreciate it if you updated this. Thank you.

**Comment by remzh** [comment]
Hi there, thanks for letting me know! 
The page has been updated to reflect those changes. 

Ryan
