### ISSUE TITLE
OK FUCK YOU YOUR FUICKING IDIOT

### ISSUE THREAD

**Issue by FUCKTART230** [Ryan778/Ryan778.github.io#6]
I PUT FUCKING POTATOES FOR THE GOOGLE FEUD FOR THE IS IT SAFE TO EAT RAW WHATEVER AND IT CAME UP AS A GOD DAMN X AND YOU MADE US LOSS YOU DUMBASS FUCKTART GO SUCK YOUR OWN DICK AND FIX IT DAMN IT.

**Comment by FUCKTART230** [comment]
i vh^$!@$o

**Comment by Ryan778** [comment]
Sorry to hear Google Feud made you upset enough to find the repository on GitHub and create an account dedicated solely to rant off. I'll be closing this issue(?) now and I strongly suggest that you take a break from the game if it causes this much duress.

**Comment by FUCKTART230** [comment]
racist little fuck

**Comment by FUCKTART230** [comment]
jk love you thank you
